/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.northwind.view;

import com.northwind.custmgr.view.CustomersWindow;
import com.northwind.enums.SysExits;
import com.northwind.settings.AppProperties;
import com.northwind.utils.Logger;
import com.northwind.utils.ScreenUtils;
import java.awt.Color;
import java.awt.SystemColor;
import java.awt.event.ActionListener;
import java.io.File;
import java.util.logging.Level;
import java.util.logging.LogRecord;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author Sean Carrick &lt;sean at pekinsoft dot com&gt;
 */
public class MainWindow extends javax.swing.JFrame implements ActionListener {
    
    private final LogRecord record;
    private final Logger log;
    private final AppProperties props;
    
    /**
     * Creates new form MainForm
     */
    public MainWindow() {
        props = AppProperties.getInstance();
        record = new LogRecord(Level.ALL, "");
        log = Logger.getInstance();
        
        record.setSourceClassName(MainWindow.class.getName());
        record.setSourceMethodName("MainWindow");
        record.setMessage("Initilizing the " + record.getSourceClassName());
        log.enter(record);
        
        initComponents();
        
        if ( props.getPropertyAsInt("main.window.state", "0") == NORMAL ) {
            setSize(props.getPropertyAsInt("main.window.width", "1080"), 
                    props.getPropertyAsInt("main.window.height", "756"));
            
            if (props.getPropertyAsInt("main.window.left", "0") == 0)
                setLocation(ScreenUtils.centerDialog(this));
            else {
                setLocation(props.getPropertyAsInt("main.window.left", "850"),
                        props.getPropertyAsInt("main.window.top", "340"));
            }
        } else {
            setExtendedState(props.getPropertyAsInt("main.window.state", 
                    String.valueOf(NORMAL)));
        }
        setTitle(props.getProjectName() + " : " + props.getVersion());
    }
    
    public static void setStatus(String msg, boolean isError) {
        tipsLabel.setText(msg);
        
        if ( isError ) 
            tipsLabel.setForeground(Color.red);
        else
            tipsLabel.setForeground(SystemColor.controlText);
    }

    private void doNewDB() {
        JFileChooser dlg = new JFileChooser();
        dlg.setDialogTitle("New Northwind Data Store");
        dlg.setFileFilter(hsqlDB);
        File dir = new File(props.getProperty("northwind.home", props.APP_DIR));
        dlg.setCurrentDirectory(dir);
        if ( dlg.showSaveDialog(this) == JFileChooser.APPROVE_OPTION ) {
            
        }
    }
    
    private void doOpenDB() {
        
    }
    
    private void doSaveDB() {
        
    }
    
    private void doExit() {
        props.setProperty("main.window.state", String.valueOf(getExtendedState()));
        if ( getExtendedState() != NORMAL ) {
            props.setPropertyAsInt("main.window.left", 0);
            props.setPropertyAsInt("main.window.top", 0);
            props.setPropertyAsInt("main.window.height", 0);
            props.setPropertyAsInt("main.window.width", 0);
        } else {
            props.setPropertyAsInt("main.window.left", getX());
            props.setPropertyAsInt("main.window.top", getY());
            props.setPropertyAsInt("main.window.height", getHeight());
            props.setPropertyAsInt("main.window.width", getWidth());
        }
        
        props.flush();
        
        props.exit(SysExits.EX_OK);
    }
    
    private void doShowCustomers() {
        CustomersWindow dlg = new CustomersWindow();
        dlg.pack();
        this.mainDesktop.add(dlg);
        dlg.setVisible(true);
    }
    
    private void doAbout() {
        String display = props.getName() + "\n" + props.getVersion() + "\n\n";
        display += props.getComments();
        
        JOptionPane.showMessageDialog(this, display, "About Northwind Traders", 
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainStatusbar = new org.jdesktop.swingx.JXStatusBar();
        tipsLabel = new javax.swing.JLabel();
        mainToolbar = new javax.swing.JToolBar();
        exitButton = new javax.swing.JButton();
        mainDesktop = new javax.swing.JDesktopPane();
        mainMenubar = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        newMenuItem = new javax.swing.JMenuItem();
        openMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        saveMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        printMenu = new javax.swing.JMenu();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        browseMenu = new javax.swing.JMenu();
        customerList = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        contentsHelpMenu = new javax.swing.JMenuItem();
        indexHelpMenu = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        aboutMenu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Northwind Traders - Basic Edition");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                cleanUpBeforeClosing(evt);
            }
        });

        tipsLabel.setText("Watch here for helpful information...");
        mainStatusbar.add(tipsLabel);

        mainToolbar.setRollover(true);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/turnoff24.png"))); // NOI18N
        exitButton.setToolTipText("Exit Northwind Traders");
        exitButton.setFocusable(false);
        exitButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        exitButton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        exitButton.setActionCommand("exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow.this.actionPerformed(evt);
            }
        });
        mainToolbar.add(exitButton);

        javax.swing.GroupLayout mainDesktopLayout = new javax.swing.GroupLayout(mainDesktop);
        mainDesktop.setLayout(mainDesktopLayout);
        mainDesktopLayout.setHorizontalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        mainDesktopLayout.setVerticalGroup(
            mainDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 226, Short.MAX_VALUE)
        );

        jMenu1.setText("File");

        newMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/newDB.png"))); // NOI18N
        newMenuItem.setMnemonic('N');
        newMenuItem.setText("New Data Store...");
        newMenuItem.setActionCommand("newDB");
        newMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow.this.actionPerformed(evt);
            }
        });
        jMenu1.add(newMenuItem);

        openMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/openDB.png"))); // NOI18N
        openMenuItem.setMnemonic('O');
        openMenuItem.setText("Open Data Store...");
        openMenuItem.setActionCommand("openDB");
        openMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow.this.actionPerformed(evt);
            }
        });
        jMenu1.add(openMenuItem);
        jMenu1.add(jSeparator1);

        saveMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/save-database.png"))); // NOI18N
        saveMenuItem.setText("Save Data Store");
        saveMenuItem.setEnabled(false);
        saveMenuItem.setActionCommand("saveDB");
        jMenu1.add(saveMenuItem);
        jMenu1.add(jSeparator2);

        printMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/print.png"))); // NOI18N
        printMenu.setMnemonic('P');
        printMenu.setText("Print");
        printMenu.setEnabled(false);
        jMenu1.add(printMenu);
        jMenu1.add(jSeparator3);

        exitMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenuItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Turn off.png"))); // NOI18N
        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow.this.actionPerformed(evt);
            }
        });
        jMenu1.add(exitMenuItem);
        exitMenuItem.setActionCommand("exit");
        exitMenuItem.getAccessibleContext().setAccessibleName("");

        mainMenubar.add(jMenu1);

        browseMenu.setText("Browse");

        customerList.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, 0));
        customerList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/users.png"))); // NOI18N
        customerList.setMnemonic('C');
        customerList.setText("Customer List");
        customerList.setActionCommand("customers");
        customerList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow.this.actionPerformed(evt);
            }
        });
        browseMenu.add(customerList);

        mainMenubar.add(browseMenu);

        helpMenu.setText("Help");

        contentsHelpMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F2, 0));
        contentsHelpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/help.png"))); // NOI18N
        contentsHelpMenu.setMnemonic('C');
        contentsHelpMenu.setText("Help Contents");
        contentsHelpMenu.setActionCommand("help");
        helpMenu.add(contentsHelpMenu);

        indexHelpMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        indexHelpMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/help-idx.png"))); // NOI18N
        indexHelpMenu.setMnemonic('i');
        indexHelpMenu.setText("Help Index");
        indexHelpMenu.setActionCommand("helpidx");
        helpMenu.add(indexHelpMenu);
        helpMenu.add(jSeparator4);

        aboutMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/info.png"))); // NOI18N
        aboutMenu.setMnemonic('N');
        aboutMenu.setText("About Northwind");
        aboutMenu.setActionCommand("about");
        aboutMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MainWindow.this.actionPerformed(evt);
            }
        });
        helpMenu.add(aboutMenu);

        mainMenubar.add(helpMenu);

        setJMenuBar(mainMenubar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainStatusbar, javax.swing.GroupLayout.DEFAULT_SIZE, 489, Short.MAX_VALUE)
            .addComponent(mainToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(mainDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(mainToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainDesktop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mainStatusbar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cleanUpBeforeClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_cleanUpBeforeClosing
        record.setSourceMethodName("cleanUpBeforeClosing");
        record.setParameters(new Object[]{evt});
        record.setMessage("Cleaning up any messes we may have left behind.");
        log.enter(record);
        
        record.setMessage("Storing window state to our preferences");
        log.debug(record);
        props.setPropertyAsInt("main.window.state", getExtendedState());
        if ( getExtendedState() == NORMAL ) {
            props.setPropertyAsInt("main.window.left", getX());
            props.setPropertyAsInt("main.window.top", getY());
            props.setPropertyAsInt("main.window.width", getWidth());
            props.setPropertyAsInt("main.window.height", getHeight());
        }
        
        
    }//GEN-LAST:event_cleanUpBeforeClosing

    @Override
    public void actionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actionPerformed
        if ( evt.getActionCommand().equalsIgnoreCase("newdb") )
            doNewDB();
        else if ( evt.getActionCommand().equalsIgnoreCase("opendb") )
            doOpenDB();
        else if ( evt.getActionCommand().equalsIgnoreCase("savedb") )
            doSaveDB();
        else if ( evt.getActionCommand().equalsIgnoreCase("exit") )
            doExit();
        else if ( evt.getActionCommand().equalsIgnoreCase("customers") )
            doShowCustomers();
        else if ( evt.getActionCommand().equalsIgnoreCase("about") )
            doAbout();
    }//GEN-LAST:event_actionPerformed
    
    private FileFilter hsqlDB = new FileFilter() {
        public String getDescription() {
            return "Northwind Data Store - HSQLDB (*.script)";
        }
        public boolean accept(File f) {
            if ( f.isDirectory() ) 
                return true;
            else if ( f.getName().endsWith(".script") )
                return true;
            else
                return false;
        }
    };
    
    //<editor-fold defaultstate="collapsed" desc="Unused main() method">
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainWindow().setVisible(true);
//            }
//        });
//    }
    //</editor-fold>

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenu;
    private javax.swing.JMenu browseMenu;
    private javax.swing.JMenuItem contentsHelpMenu;
    private javax.swing.JMenuItem customerList;
    private javax.swing.JButton exitButton;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuItem indexHelpMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JDesktopPane mainDesktop;
    private javax.swing.JMenuBar mainMenubar;
    private org.jdesktop.swingx.JXStatusBar mainStatusbar;
    private javax.swing.JToolBar mainToolbar;
    private javax.swing.JMenuItem newMenuItem;
    private javax.swing.JMenuItem openMenuItem;
    private javax.swing.JMenu printMenu;
    private javax.swing.JMenuItem saveMenuItem;
    private static javax.swing.JLabel tipsLabel;
    // End of variables declaration//GEN-END:variables

}
