/*
 * Copyright (C) 2020 PekinSOFT Systems
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
package com.northwind.view.options;

import com.northwind.settings.AppProperties;
import com.northwind.utils.ScreenUtils;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Sean Carrick &lt;sean at pekinsoft dot com&gt;
 */
public class GlobalOptionsDlg extends javax.swing.JDialog {
    
    private String appHome;
    private String dataHome;
    private String logHome;
    private String errHome;
    private boolean isDirty;
    private boolean isLoading;
    private AppProperties props;
    
    /**
     * Creates new form GlobalOptionsDlg
     */
    public GlobalOptionsDlg(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        isLoading = true;
        
        props = AppProperties.getInstance();
        
        initComponents();
        
        // Load the defaults based on OS.
        if ( System.getProperty("os.name").equalsIgnoreCase("windows") ) {
            appHome = System.getProperty("user.home") + File.separator 
                    + "AppData" + File.separator + "Local" + File.separator 
                    + "Northwind Traders" + File.separator;
        } else {
            appHome = System.getProperty("user.home") + File.separator 
                    + ".northwind" + File.separator;
        }
        
        dataHome = appHome + "data" + File.separator;
        logHome = appHome + "var" + File.separator + "logs" + File.separator;
        errHome = appHome + "var" + File.separator + "err" + File.separator;
        
        this.appHomePath.setText(props.getProperty("app.home", appHome));
        this.defaultDataFolder.setText(props.getProperty("data.home", dataHome));
        this.logsLocation.setText(props.getProperty("logs.home", logHome));
        this.errLogLocation.setText(props.getProperty("err.home", errHome));
        
        this.setLocation(ScreenUtils.centerDialog(this));
        
        isDirty = false;
        
        isDirty = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandPanel = new javax.swing.JPanel();
        cancelButton = new javax.swing.JButton();
        saveButton = new javax.swing.JButton();
        globalTabs = new javax.swing.JTabbedPane();
        companyTab = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        companyName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        businessForm = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        address = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        suite = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        city = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        state = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        zipCode = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        phoneNumber = new javax.swing.JFormattedTextField();
        faxNumber = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        contactName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        emailAddress = new javax.swing.JTextField();
        programTab = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        appHomePath = new javax.swing.JTextField();
        browseAppLocationButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        dbDriver = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        dbDriverConnURL = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        defaultDBName = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        dbConnOptions = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        defaultDataFolder = new javax.swing.JTextField();
        browseDbLocationButton = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        logsLocation = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        errLogLocation = new javax.swing.JTextField();
        browseLogLocationButton = new javax.swing.JButton();
        browseErrorLogLocationButton = new javax.swing.JButton();
        browseDbFileLocationButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Northwind Traders Global Options");
        setUndecorated(true);
        setResizable(false);

        cancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Cancel.png"))); // NOI18N
        cancelButton.setMnemonic('C');
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doCancel(evt);
            }
        });

        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Apply.png"))); // NOI18N
        saveButton.setMnemonic('S');
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doSave(evt);
            }
        });

        javax.swing.GroupLayout commandPanelLayout = new javax.swing.GroupLayout(commandPanel);
        commandPanel.setLayout(commandPanelLayout);
        commandPanelLayout.setHorizontalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(saveButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelButton)
                .addContainerGap())
        );
        commandPanelLayout.setVerticalGroup(
            commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, commandPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(commandPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelButton)
                    .addComponent(saveButton))
                .addContainerGap())
        );

        jLabel1.setText("Company Name:");

        companyName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel2.setText("Business Form:");

        businessForm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sole Proprietor", "Limited Liability Company", "Limited Liability Partnership", "\"S\" Corporation", "Incorporated" }));
        businessForm.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setDirtyCombo(evt);
            }
        });

        jLabel3.setText("Address:");

        address.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel4.setText("Suite/Box:");

        suite.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel5.setText("City:");

        city.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel6.setText("State:");

        state.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel7.setText("Zip Code:");

        zipCode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel8.setText("Phone Number:");

        try {
            phoneNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        try {
            faxNumber.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###) ###-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        faxNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel9.setText("Fax Number:");

        jLabel10.setText("Contact Name:");

        contactName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel11.setText("Email Address:");

        emailAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        javax.swing.GroupLayout companyTabLayout = new javax.swing.GroupLayout(companyTab);
        companyTab.setLayout(companyTabLayout);
        companyTabLayout.setHorizontalGroup(
            companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel8)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(companyTabLayout.createSequentialGroup()
                        .addComponent(companyName, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(businessForm, 0, 160, Short.MAX_VALUE))
                    .addGroup(companyTabLayout.createSequentialGroup()
                        .addComponent(address)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(suite, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyTabLayout.createSequentialGroup()
                        .addComponent(city)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyTabLayout.createSequentialGroup()
                        .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(faxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(companyTabLayout.createSequentialGroup()
                        .addComponent(contactName, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(emailAddress))))
        );
        companyTabLayout.setVerticalGroup(
            companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(companyTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(companyName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(businessForm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(suite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(city, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(state, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(zipCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(phoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faxNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(companyTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(contactName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(emailAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(96, Short.MAX_VALUE))
        );

        globalTabs.addTab("Company Information", new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Company.png")), companyTab); // NOI18N

        jLabel12.setText("Where do you want to store Northwind settings and data?");

        appHomePath.setText("{USER_HOME}/.northwind/");
        appHomePath.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        browseAppLocationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Find.png"))); // NOI18N
        browseAppLocationButton.setActionCommand("appHome");
        browseAppLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBrowse(evt);
            }
        });

        jLabel13.setText("Which database driver to you want to use?");

        dbDriver.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Embedded <HSQLDB>", "Apache Derby <Embedded>", "Apache Derby <Server>", "Microsoft SQL Server", "MySQL Server", "PostGres SQL Server" }));
        dbDriver.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                setDirtyCombo(evt);
            }
        });

        jLabel14.setText("Driver Connection URL:");

        dbDriverConnURL.setText("jdbc:hsqldb:");
        dbDriverConnURL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel15.setText("Default Database Name:");

        defaultDBName.setText("northwind_db");
        defaultDBName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel16.setText("Default Connection Options:");

        dbConnOptions.setText(";shutdown=true");
        dbConnOptions.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel17.setText("Default Data Store Location:");

        defaultDataFolder.setText("{APP_DIR}/data/");
        defaultDataFolder.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        browseDbLocationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Find.png"))); // NOI18N
        browseDbLocationButton.setActionCommand("dataHome");
        browseDbLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBrowse(evt);
            }
        });

        jLabel18.setText("Default Logs Location:");

        logsLocation.setText("{APP_DIR}/var/logs/");
        logsLocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        jLabel19.setText("Default Error Report Location:");

        errLogLocation.setText("{APP_DIR}/var/err/");
        errLogLocation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                setDirty(evt);
            }
        });

        browseLogLocationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Find.png"))); // NOI18N
        browseLogLocationButton.setActionCommand("logsHome");
        browseLogLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBrowse(evt);
            }
        });

        browseErrorLogLocationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Find.png"))); // NOI18N
        browseErrorLogLocationButton.setActionCommand("errHome");
        browseErrorLogLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBrowse(evt);
            }
        });

        browseDbFileLocationButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Find.png"))); // NOI18N
        browseDbLocationButton.setActionCommand("dataHome");
        browseDbFileLocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBrowse(evt);
            }
        });
        browseDbFileLocationButton.setActionCommand("dbFileHome");

        javax.swing.GroupLayout programTabLayout = new javax.swing.GroupLayout(programTab);
        programTab.setLayout(programTabLayout);
        programTabLayout.setHorizontalGroup(
            programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel17)
                    .addComponent(jLabel16)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(programTabLayout.createSequentialGroup()
                        .addComponent(appHomePath)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseAppLocationButton))
                    .addComponent(dbDriver, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dbDriverConnURL)
                    .addComponent(dbConnOptions)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, programTabLayout.createSequentialGroup()
                        .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(errLogLocation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(logsLocation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(defaultDataFolder))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(browseDbLocationButton)
                            .addComponent(browseLogLocationButton)
                            .addComponent(browseErrorLogLocationButton)))
                    .addGroup(programTabLayout.createSequentialGroup()
                        .addComponent(defaultDBName, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(browseDbFileLocationButton)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        programTabLayout.setVerticalGroup(
            programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(programTabLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(appHomePath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(browseAppLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dbDriver, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(dbDriverConnURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel15)
                        .addComponent(defaultDBName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(browseDbFileLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(dbConnOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(defaultDataFolder, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(browseDbLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel18)
                        .addComponent(logsLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(browseLogLocationButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(programTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel19)
                        .addComponent(errLogLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(browseErrorLogLocationButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        globalTabs.addTab("Northwind Settings", new javax.swing.ImageIcon(getClass().getResource("/com/northwind/resources/Northwind16.png")), programTab); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(commandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(globalTabs))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(globalTabs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commandPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void doCancel(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doCancel
        // Close the window without saving the changes, if any, but prompt the
        //+ user first if changes were made.
        if ( this.isDirty ) {
            String msg = "Do you want to save your changes?";
            String ttl = "Confirm Cancel";
            int opt = JOptionPane.showConfirmDialog(this, msg, ttl, 
                    JOptionPane.YES_NO_OPTION);
            if ( opt == JOptionPane.YES_OPTION )
            
            doSave(evt);
        }
        this.dispose();
    }//GEN-LAST:event_doCancel

    private void doBrowse(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doBrowse
        // We are going to handle showing the File browser for all browse 
        //+ buttons in this event. We will use their ActionCommand value to
        //+ determine:
        //+     
        //+     A) The title of the file chooser dialog
        //+     B) which text field to update
        String which = evt.getActionCommand();
        
        String dlgTitle = "Choose Folder";
        
        if ( which.equalsIgnoreCase("apphome") )
            dlgTitle = "Choose Northwind Home Folder";
        else if ( which.equalsIgnoreCase("datahome") )
            dlgTitle = "Choose Northwind Data Folder";
        else if ( which.equalsIgnoreCase("logshome") )
            dlgTitle = "Choose Northwind Logs Folder";
        else if ( which.equalsIgnoreCase("errhome") )
            dlgTitle = "Choose Northwind Error Reports Folder";
        else if ( which.equalsIgnoreCase("dbfilehome") )
            dlgTitle = "Choose Location for Data Store File";
        
        JFileChooser choose = new JFileChooser();
        choose.setDialogTitle(dlgTitle);
        choose.setCurrentDirectory(new File(System.getProperty("user.home")));
        
        if ( !which.equalsIgnoreCase("dbfilehome") )
            choose.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        else
            choose.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES);
        
        choose.setMultiSelectionEnabled(false);
        int option = choose.showDialog(this, "Select");
        
        if ( option == JFileChooser.APPROVE_OPTION ) {
            
            File file = choose.getSelectedFile();
            
            if ( which.equalsIgnoreCase("apphome") )
                this.appHomePath.setText(file.getAbsolutePath() 
                        + File.separator);
            else if ( which.equalsIgnoreCase("datahome") )
                this.defaultDataFolder.setText(file.getAbsolutePath() 
                        + File.separator);
            else if ( which.equalsIgnoreCase("logshome") )
                this.logsLocation.setText(file.getAbsolutePath() 
                        + File.separator);
            else if ( which.equalsIgnoreCase("errhome") )
                this.errLogLocation.setText(file.getAbsolutePath()
                        + File.separator);
            else if ( which.equalsIgnoreCase("dbfilehome") )
                this.errLogLocation.setText(file.getAbsolutePath());
            
            this.isDirty = true;
        }
        
        choose = null;
        
    }//GEN-LAST:event_doBrowse

    private void setDirtyCombo(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_setDirtyCombo
        // Flag the dialog data as having been changed, but only if the dialog
        //+ is NOT being loaded.
        if ( !this.isLoading )
            this.isDirty = true;
    }//GEN-LAST:event_setDirtyCombo

    private void setDirty(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_setDirty
        // Set our dirty flag if any of the data changes.
        isDirty = true;
    }//GEN-LAST:event_setDirty

    private void doSave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doSave
        // If the user clicks on the Save button, we are going to check to see
        //+ if our dirty flag is set. If not, there is no need to save, so we
        //+ will just close the dialog.
        if ( this.isDirty ) {
            props.setDataFolder(this.defaultDataFolder.getText());
            props.setProperty("app.home", this.appHomePath.getText());
            props.setProperty("logs.home", this.logsLocation.getText());
            props.setProperty("err.home", this.errLogLocation.getText());
            props.setProperty("db.name", this.defaultDBName.getText());
            props.setProperty("db.driver", 
                    this.dbDriver.getSelectedItem().toString());
            props.setProperty("db.url", this.dbDriverConnURL.getText());
            props.setProperty("db.options", 
                    this.dbConnOptions.getText());
            this.isDirty = false;
        }
        
        doCancel(evt);
    }//GEN-LAST:event_doSave

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GlobalOptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GlobalOptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GlobalOptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GlobalOptionsDlg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                GlobalOptionsDlg dialog = new GlobalOptionsDlg(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address;
    private javax.swing.JTextField appHomePath;
    private javax.swing.JButton browseAppLocationButton;
    private javax.swing.JButton browseDbFileLocationButton;
    private javax.swing.JButton browseDbLocationButton;
    private javax.swing.JButton browseErrorLogLocationButton;
    private javax.swing.JButton browseLogLocationButton;
    private javax.swing.JComboBox<String> businessForm;
    private javax.swing.JButton cancelButton;
    private javax.swing.JTextField city;
    private javax.swing.JPanel commandPanel;
    private javax.swing.JTextField companyName;
    private javax.swing.JPanel companyTab;
    private javax.swing.JTextField contactName;
    private javax.swing.JTextField dbConnOptions;
    private javax.swing.JComboBox<String> dbDriver;
    private javax.swing.JTextField dbDriverConnURL;
    private javax.swing.JTextField defaultDBName;
    private javax.swing.JTextField defaultDataFolder;
    private javax.swing.JTextField emailAddress;
    private javax.swing.JTextField errLogLocation;
    private javax.swing.JFormattedTextField faxNumber;
    private javax.swing.JTabbedPane globalTabs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField logsLocation;
    private javax.swing.JFormattedTextField phoneNumber;
    private javax.swing.JPanel programTab;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField state;
    private javax.swing.JTextField suite;
    private javax.swing.JTextField zipCode;
    // End of variables declaration//GEN-END:variables
}
